let handler  = async (m, { conn }) => {
  conn.reply(m.chat,`*┌────「 HOLA ¿QUE TAL? 」─*\n*“${pickRandom(global.verdad)}”*\n*└────「 PAIN-BOT 」─*`, m)
}
handler.help = ['verdad']
handler.tags = ['General']
handler.customPrefix = /Hola|hola|ola|Ola|hello|Hello/
handler.command = new RegExp
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

global.verdad = [
"¿Alguna vez te ha gustado alguien? ¿Cuánto tiempo?",
  "Si es posible o si quieres, en gc / fuera de gc, ¿con quién harás amistad? (Puede ser diferente / del mismo tipo)",
  "¿cual es tu mas grande miedo?",
  "¿Alguna vez te ha gustado alguien y has sentido a esa persona como tú también?",
  "¿Cuál es el nombre del exnovio de tu amiga que una vez te gustó en secreto?",
  "¿Alguna vez has robado el dinero de tu madre o de tu padre? ¿La razón?",
  "lo que te hace feliz cuando estás triste",
  "¿Alguna vez has sido amor no correspondido? ¿Si has estado con quién? ¿Cómo se siente brou?",
  "¿Alguna vez has tenido una aventura con alguien?",
  "quién es la persona más influyente en tu vida",
  "qué orgullo tienes este año",
  "quién es la persona que puede enfermarte",
  "quien es la persona que alguna vez te puso cachondo",
  "(para los musulmanes) ¿nunca has rezado en todo el día?",
  "¿Quién es el más cercano a su tipo de pareja ideal aquí",
  "¿Con quién te gusta jugar?",
  "¿Alguna vez has rechazado a alguien? ¿Por qué?",
  "Menciona el incidente que te hizo daño y que aún recuerdas",
  "¿Qué logros has obtenido este año?",
  "¿Cuál es tu peor hábito en la escuela?", "¿Qué programa de televisión odias más? ¡Da la razón!", "¿Cuál es el vestido más feo (en su opinión) que ha usado y cuándo lo usó?", "¿Qué es lo peor (chisme) que has dicho sobre tu amigo?","¿Qué es lo más vergonzoso de ti?"," ¿Qué es lo primero que ves cuando miras a otra persona (del sexo opuesto)?", 
"¿Qué es lo primero que te viene a la mente cuando te miras al espejo?","¿Que es lo mas tonto que has hecho en tu vida?"," ¿Cuál es el peor sueño que has tenido?"," ¿Cuál es el sueño más loco que puedes recordar hasta ahora?",
" ¿Cuál es tu peor rasgo en tu opinión?", 
" ¿Qué rasgo te gustaría cambiar de ti mismo?", 
" ¿Qué rasgo te gustaría cambiar en tu amigo?", 
" ¿Qué harías si tu novio te dijera que tienes mala nariz o dedos?", 
" ¿En qué piensas antes de dormir? ej .: fantasear con una pareja, etc.", 
"¿Qué crees que se destaca más de ti?"," ¿Qué parte del cuerpo de tu amigo te gusta más y desearías tener?", 
"¿Qué parte de tu cuerpo odias más?"," De todas las clases de la escuela, ¿a qué clase le gustaría ingresar y qué clase le gustaría evitar?", 
"¡Describe a tu amigo más cercano!"," ¡Descríbete en una palabra!"," ¿Qué películas y canciones te han hecho llorar?", 
" alguien del grupo esta enamorado de ti y no te lo quiere contar", 
" ¿Qué es lo más romántico que alguien (del sexo opuesto) te ha hecho o regalado?", 
"¿Qué es lo más desagradable que has experimentado?", 
" Si nacieras de nuevo y tuvieras que ser uno de tus amigos, ¿a quién elegirías ser?", 
" Eserio, aveces eres tan tonto que me sorprendes", 
" Si el apocalipsis llega pronto, ¿qué haces?", 
" Si te pagaran una cirugia sea cual sea ¿Que cirugia te harias tu?", 
" Alguna vez has robado algo?", 
" ¿Tiene miedo a morir? ¿Por qué?", 
" ¿Cuándo fue la última vez que lloraste y por qué?", 
" ¿Cuáles son tus habilidades especiales? aparte de hacerte el pendejo", 
" ¿Tu que opinas, realmente el tamaño importa o no?", 
" ¿Cuál crees que es un buen rasgo de tu amigo más cercano que él o ella no conozca?", 
" ¿Con qué tipo de persona te gustaría casarte algún día?", 
" En tu opinión, ¿Que es lo mas atractivo que tiene la persona que puso el msj arriba del mio?", 
" ¿Con quién quieres intercambiar por un día? (amigos más cercanos que ambos conocen) y por qué", 
" ¿Alguna vez has esperado en secreto que la relación de alguien con su novia se rompiera? ¿Quién?", 
" ¿Prefiere AMIGAS o AMIGOS? ¿Por qué?", 
" ¿Qué cita recuerdas más y te gusta?",
" ¿Vez mal que alguien haga el amor en la primera cita?", 
" ¿Qué secretos nunca les has contado a tus amigos hasta ahora?", 
" ¿Quiénes son sus verdaderos modelos a seguir?", 
" ¿Cuál de tus amigos crees que tiene el cabello mas bonito?", 
" ¿Cuál de tus amigos crees que tiene el peor corte de pelo?", 
" ¿Cuál de tus amigos es el más fotogénico? ", 
" ¿Quién es tu mejor ex? ¡¿Y por qué rompieron si te lo hacia tan rico?!", 
" ¿haz tenido un amorio con alguno de tus profesor@s?", 
" ¿Cómo se llamaba el profesor que te gustaba?", 
" ¿Cuál es el nombre de la exnovia de tu amigo que te ha gustado en secreto?", 
" ¿Cuál es el nombre de la persona (del sexo opuesto) que crees que sería divertido ser novia?", 
" ¿Cuál es el nombre de la persona que odias, pero crees que le gustas a esa persona (no necesariamente del sexo opuesto)?", 
" ¿Cuál es el nombre de la persona a la que has estado señalando en secreto?", 
" ¿Quién es la persona (del sexo opuesto) que más se te pasa por la cabeza?", 
" ¿Quién es la persona más molesta entre tus amigos? ¡la razón!", 
" ¿A quién de tus amigos crees que debería renovarse?", 
" ¿Quién está más cerca de ser tu pareja ideal aquí?", 
"Padre o madre", 
"Que parte del cuerpo no te gusta", 
"¿Alguna vez has hecho trampa en el juego?", 
"¿Que es lo que mas te gusta hacer en la cama?", 
"¿Qué es lo primero que harías si te despertaras como del sexo opuesto?", 
"¿Alguna vez has dejado que alguien más se meta en problemas por algo que hiciste?", 
"¿Perdonarias una infidelidad?", 
" ¿Cuál es la razón más ridícula por la que has roto con alguien?", 
" ¿Cuál es el peor hábito que tienes?", 
" ¿Cuál crees que es tu mejor característica? ¿Y que es lo peor?", 
" ¿Cuál es la cosa más valiente que has hecho?", 
" ¿Cuándo fue la última vez que mojaste la cama?", 
" ¿Con qué sueñas más cuando duermes?", 
" ¿Crees que no me entero lo que estas haciendo a escondidas?", 
" ¿Qué cosas infantiles sigues creyendo? aparte de creer que el/ella esta enamorad@ de ti", 
" ¿Te consideras una persona atractiva? si es asi manda una foto", 
" ¿Qué es lo que más te impresiona de esa persona a la que elegiste querer?", 
" Si se le permitiera usar solo 3 palabras durante el resto de la noche a partir de ahora, ¿cuáles serían?", 
" Si fueras un dictador, ¿qué ley promulgarías primero?", 
"Si vivieras durante la era nazi, ¿quién serías?", 
"¿Cuál fue la experiencia más vergonzosa en la escuela? tuve un amigo que se tiro un pedo y sele salio la cosa aquella", 
"¿Cuál es el mayor error de tu vida? aparte de enamorarte de alguien que te rompio el corazon que pena", 
"¿Qué no harías nunca, incluso si supieras que solo te quedan 12 horas de vida?", 
" ¿Qué delitos has cometido?", 
" Cuéntame un secreto de tu infancia.", 
" La masturbacion no te llevara a ningun lado, ya dejala", 
" ¿Qué quieres hacer conmigo… ( x persona), si luego puedes borrar su memoria (él,…)?", 
" ¿Qué es lo peor que le has hecho a alguien?", 
" ¿Quién te gusta más?", 
"¿Haz tenido un relacion oculta con alguien del mundo parchis?", 
" Si fueras un vampiro, ¿a cuál de nosotros morderías ahora?", 
" ¿Ha defecado alguna vez en público? jajaja aunque digas que no ya te conocemos pero tenias diarrea ese dia asi que no pasa nada", 
" ¿Cuál es tu fantasía más oscura?", 
" ¿Qué es lo mejor que has tenido con alguien a nivel de amorio?", 
" ¿Cuál es el mayor desafio del dia a dia para ti?", 
" ¿Qué es lo que más te gusta de tu cuerpo y lo que menos te gusta?", 
" ¿A quien te gustaría ver desnuda o desnudo de este grupo?", 
" ¿Quién en este grupo crees que puede enamorarte?", 
" ¿Alguna vez has tenido un sueño erótico y te has levantado mojada/o?", 
" Si te vas a tatuar, ¿que tatuaje te harias?", 
" ¿Qué es más importante en una relación: el sexo el amor o el dinero?", 
" ¿Crees que el sexo es genial, bueno, divertido a veces, o realmente no te importa?", 
" ¿Crees que exista una persona que se merezca los latidos de tu corazon?", 
"¿Cuántas veces a la semana / mes tiene relaciones sexuales y con qué frecuencia desea tener relaciones sexuales?", 
" ¿Alguna vez te has planteado hacer un trio?",
" ¿Qué parte de tu cuerpo crees que atrae mas a las personas?", 
" ¿Cómo, dónde y con quién tuviste tu primer beso?", 
" ¿Qué importancia tienen para ti los juegos previos prolongados en el acto sexual?", 
" ¿Qué debe hacer un hombre o una mujer para seducirte?", 
" ¿Alguna vez has tenido sexo con un buen amigo?", 
" ¿Alguna vez ha tenido relaciones sexuales con alguien de estos grupos?", 
"¿Qué animal se adapta mejor a ti y por qué? yo creo que el cerdo te queda", 
" ¿Cuál fue tu peor cita?", 
" Si te concedieran un deseo ¿Que desearias?", 
" ¿Cuál es tu oscura fantasía secreta?", 
" ¿Prefieres tatuarte el culo o perforarte la lengua?", 
" ¿Eres siempre leal o solo lo aparentas?", 
" En la adolesencia cometemos muchas locuras ¿Cual fue la mas grande que cometiste?", 
" ¿De qué persona te enamoraste y te mintio?", 
" ¿Con qué celebridad te gustaría salir?", 
" ¿Alguna vez te has cagado encima? no son preguntas tontas hay personas que lo han hecho", 
" ¿Qué boca te gusta más del grupo de aquí?", 
" ¿Qué jugador tiene la mano más hermosa?", 
" ¿Dónde fue tu primer beso? si es que lo recuerdas", 
" ¿A quién del grupo te gustaría besar más?", 
" ¿Quién en la mesa es quizás el más divertido?", 
" ¿Cuál es el mayor error de tu vida? aparte de ser un pendejo", 
" ¿Te pasó algo vergonzoso en una cita?", 
" ¿Has estado alguna vez en contacto con las drogas?", 
" ¿A qué persona quieres besar ahora?", 
" ¿Cuándo fue la última vez que estuviste borracho?", 
" ¿Alguna vez has hecho trampa en un examen escolar? si me respondes que no te bloqueo", 
" ¿Has robado algo en el pasado?", 
" ¿Roncas por la noche?", 
" ¿Cuales tu cancion favorita?", 
" ¿Con qué jugadores de parchis te gusta jugar mas? deben estar en el grupo", 
" si te mudas a una isla desierta, ¿a quién te llevarias de aquí?", 
" ¿A que temes más en la vida?", 
" ¿Dónde te afeitas? ¿en todas partes? si eres hombre y respondes en todas partes, por ahi dicen que el que limpia el patio es porque espera visita uyyyy malvado", 
"¿Tienes un apodo? dime cual es", 
" ¿Cuantas veces vas al baño en el dia cagon/a?", 
"¿Quién te dio la peor angustia?", 
"¿Cual ha sido tu relacion amorosa mas larga?", 
"¿Qué es lo más embarazoso que te ha pasado? y no me digas que cuando caiste embarazada", 
"¿Cuántos chicos / chicas has besado? si no respondes supondre que son demasiados", 
"¿De quien estas enamorado(a) en el grupo? recuerda que todos mienten", 
"Que estrella te gusta", 
"¿Empezaste algo con X o Y persona? (insertar nombre) si te atreves", 
"Alguna vez has robado algo?",
"Hola, dime ¿que es lo mas asqueroso que has hecho?",
"Hola Eres GEY?",
"Cuantos dias has durado sin bañarte",
"¿Que posicion sexual es la que mas te gusta?",
"¿Haz tenido una relacion amorosa con dos personas distintas al mismo tiempo?",
"¿Cual es tu motivo para seguir adelante?"

] 
